// Usage: DATABASE_URL=... npm run db:migrate        (creates/updates all tables)
//        npm run db:schema                          (writes db/schema.sql for pasting into the Neon SQL editor)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildDDL } from '../src/ddl.js';
import { PgStore } from '../src/pgStore.js';

const here = path.dirname(fileURLToPath(import.meta.url));

if (process.argv.includes('--print')) {
  const sql = `-- Generated by backend/scripts/migrate.js (npm run db:schema). Idempotent.\n\n${buildDDL().join('\n\n')}\n`;
  fs.writeFileSync(path.join(here, '..', 'db', 'schema.sql'), sql);
  console.log('Wrote backend/db/schema.sql');
} else {
  if (!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required');
  const store = new PgStore(process.env.DATABASE_URL);
  await store.init();
  await store.close();
  console.log('Database schema is up to date.');
}
