-- Generated by backend/scripts/migrate.js (npm run db:schema). Idempotent.

CREATE TABLE IF NOT EXISTS "activity_logs" (
  id uuid PRIMARY KEY,
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now(),
  created_by text,
  "action_type" text,
  "entity_type" text,
  "entity_id" text,
  "entity_name" text,
  "performed_by" text,
  "performed_by_name" text,
  "performed_by_role" text,
  "changes" jsonb,
  "timestamp" text,
  extra jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE "activity_logs" ADD COLUMN IF NOT EXISTS "action_type" text;

ALTER TABLE "activity_logs" ADD COLUMN IF NOT EXISTS "entity_type" text;

ALTER TABLE "activity_logs" ADD COLUMN IF NOT EXISTS "entity_id" text;

ALTER TABLE "activity_logs" ADD COLUMN IF NOT EXISTS "entity_name" text;

ALTER TABLE "activity_logs" ADD COLUMN IF NOT EXISTS "performed_by" text;

ALTER TABLE "activity_logs" ADD COLUMN IF NOT EXISTS "performed_by_name" text;

ALTER TABLE "activity_logs" ADD COLUMN IF NOT EXISTS "performed_by_role" text;

ALTER TABLE "activity_logs" ADD COLUMN IF NOT EXISTS "changes" jsonb;

ALTER TABLE "activity_logs" ADD COLUMN IF NOT EXISTS "timestamp" text;

CREATE INDEX IF NOT EXISTS "activity_logs_entity_id_idx" ON "activity_logs" ("entity_id");

CREATE TABLE IF NOT EXISTS "daily_tasks" (
  id uuid PRIMARY KEY,
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now(),
  created_by text,
  "date" text,
  "project_id" text,
  "user_id" text,
  "task" text,
  "expected_outcome" text,
  "expected_time" double precision,
  "tasks_done" text,
  "actual_time_taken" double precision,
  "task_status" text,
  "priority" text,
  "notes" text,
  "file_source" text,
  "assigned_by" text,
  extra jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "date" text;

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "project_id" text;

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "user_id" text;

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "task" text;

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "expected_outcome" text;

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "expected_time" double precision;

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "tasks_done" text;

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "actual_time_taken" double precision;

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "task_status" text;

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "priority" text;

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "notes" text;

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "file_source" text;

ALTER TABLE "daily_tasks" ADD COLUMN IF NOT EXISTS "assigned_by" text;

CREATE INDEX IF NOT EXISTS "daily_tasks_project_id_idx" ON "daily_tasks" ("project_id");

CREATE INDEX IF NOT EXISTS "daily_tasks_user_id_idx" ON "daily_tasks" ("user_id");

CREATE TABLE IF NOT EXISTS "file_uploads" (
  id uuid PRIMARY KEY,
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now(),
  created_by text,
  "filename" text,
  "file_type" text,
  "file_url" text,
  "uploaded_by" text,
  "project_id" text,
  "status" text,
  "records_imported" double precision,
  "errors" jsonb,
  "column_mapping" jsonb,
  extra jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE "file_uploads" ADD COLUMN IF NOT EXISTS "filename" text;

ALTER TABLE "file_uploads" ADD COLUMN IF NOT EXISTS "file_type" text;

ALTER TABLE "file_uploads" ADD COLUMN IF NOT EXISTS "file_url" text;

ALTER TABLE "file_uploads" ADD COLUMN IF NOT EXISTS "uploaded_by" text;

ALTER TABLE "file_uploads" ADD COLUMN IF NOT EXISTS "project_id" text;

ALTER TABLE "file_uploads" ADD COLUMN IF NOT EXISTS "status" text;

ALTER TABLE "file_uploads" ADD COLUMN IF NOT EXISTS "records_imported" double precision;

ALTER TABLE "file_uploads" ADD COLUMN IF NOT EXISTS "errors" jsonb;

ALTER TABLE "file_uploads" ADD COLUMN IF NOT EXISTS "column_mapping" jsonb;

CREATE INDEX IF NOT EXISTS "file_uploads_project_id_idx" ON "file_uploads" ("project_id");

CREATE TABLE IF NOT EXISTS "projects" (
  id uuid PRIMARY KEY,
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now(),
  created_by text,
  "name" text,
  "description" text,
  "team_id" text,
  "project_manager_id" text,
  "assigned_members" jsonb,
  "start_date" text,
  "end_date" text,
  "status" text,
  "priority" text,
  "budget" double precision,
  "progress" double precision,
  extra jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "name" text;

ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "description" text;

ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "team_id" text;

ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "project_manager_id" text;

ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "assigned_members" jsonb;

ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "start_date" text;

ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "end_date" text;

ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "status" text;

ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "priority" text;

ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "budget" double precision;

ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "progress" double precision;

CREATE INDEX IF NOT EXISTS "projects_team_id_idx" ON "projects" ("team_id");

CREATE INDEX IF NOT EXISTS "projects_project_manager_id_idx" ON "projects" ("project_manager_id");

CREATE TABLE IF NOT EXISTS "project_resources" (
  id uuid PRIMARY KEY,
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now(),
  created_by text,
  "project_id" text,
  "title" text,
  "description" text,
  "type" text,
  "content" text,
  "file_name" text,
  "file_size" double precision,
  "uploaded_by" text,
  "is_active" boolean,
  extra jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE "project_resources" ADD COLUMN IF NOT EXISTS "project_id" text;

ALTER TABLE "project_resources" ADD COLUMN IF NOT EXISTS "title" text;

ALTER TABLE "project_resources" ADD COLUMN IF NOT EXISTS "description" text;

ALTER TABLE "project_resources" ADD COLUMN IF NOT EXISTS "type" text;

ALTER TABLE "project_resources" ADD COLUMN IF NOT EXISTS "content" text;

ALTER TABLE "project_resources" ADD COLUMN IF NOT EXISTS "file_name" text;

ALTER TABLE "project_resources" ADD COLUMN IF NOT EXISTS "file_size" double precision;

ALTER TABLE "project_resources" ADD COLUMN IF NOT EXISTS "uploaded_by" text;

ALTER TABLE "project_resources" ADD COLUMN IF NOT EXISTS "is_active" boolean;

CREATE INDEX IF NOT EXISTS "project_resources_project_id_idx" ON "project_resources" ("project_id");

CREATE TABLE IF NOT EXISTS "sheet_syncs" (
  id uuid PRIMARY KEY,
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now(),
  created_by text,
  "user_id" text,
  "sheet_id" text,
  "last_sync" text,
  "sync_status" text,
  "error_message" text,
  extra jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE "sheet_syncs" ADD COLUMN IF NOT EXISTS "user_id" text;

ALTER TABLE "sheet_syncs" ADD COLUMN IF NOT EXISTS "sheet_id" text;

ALTER TABLE "sheet_syncs" ADD COLUMN IF NOT EXISTS "last_sync" text;

ALTER TABLE "sheet_syncs" ADD COLUMN IF NOT EXISTS "sync_status" text;

ALTER TABLE "sheet_syncs" ADD COLUMN IF NOT EXISTS "error_message" text;

CREATE INDEX IF NOT EXISTS "sheet_syncs_user_id_idx" ON "sheet_syncs" ("user_id");

CREATE INDEX IF NOT EXISTS "sheet_syncs_sheet_id_idx" ON "sheet_syncs" ("sheet_id");

CREATE TABLE IF NOT EXISTS "tasks" (
  id uuid PRIMARY KEY,
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now(),
  created_by text,
  "title" text,
  "description" text,
  "project_id" text,
  "assigned_to" text,
  "status" text,
  "priority" text,
  "due_date" text,
  "estimated_hours" double precision,
  "actual_hours" double precision,
  "notes" text,
  "category" text,
  "required_skills" jsonb,
  "tags" jsonb,
  "campaign" text,
  extra jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "title" text;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "description" text;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "project_id" text;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "assigned_to" text;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "status" text;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "priority" text;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "due_date" text;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "estimated_hours" double precision;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "actual_hours" double precision;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "notes" text;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "category" text;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "required_skills" jsonb;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "tags" jsonb;

ALTER TABLE "tasks" ADD COLUMN IF NOT EXISTS "campaign" text;

CREATE INDEX IF NOT EXISTS "tasks_project_id_idx" ON "tasks" ("project_id");

CREATE TABLE IF NOT EXISTS "teams" (
  id uuid PRIMARY KEY,
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now(),
  created_by text,
  "name" text,
  "description" text,
  "team_leaders" jsonb,
  "team_members" jsonb,
  "is_active" boolean,
  extra jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "name" text;

ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "description" text;

ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "team_leaders" jsonb;

ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "team_members" jsonb;

ALTER TABLE "teams" ADD COLUMN IF NOT EXISTS "is_active" boolean;

CREATE TABLE IF NOT EXISTS "team_members" (
  id uuid PRIMARY KEY,
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now(),
  created_by text,
  "name" text,
  "role" text,
  "email" text,
  "skills" jsonb,
  "availability" double precision,
  "current_workload" double precision,
  extra jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "name" text;

ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "role" text;

ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "email" text;

ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "skills" jsonb;

ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "availability" double precision;

ALTER TABLE "team_members" ADD COLUMN IF NOT EXISTS "current_workload" double precision;

CREATE TABLE IF NOT EXISTS "users" (
  id uuid PRIMARY KEY,
  created_date timestamptz NOT NULL DEFAULT now(),
  updated_date timestamptz NOT NULL DEFAULT now(),
  created_by text,
  "full_name" text,
  "email" text,
  "role" text,
  "status" text,
  "project_ids" jsonb,
  "google_sheet_id" text,
  "designation" text,
  "contact" text,
  "hire_date" text,
  "skills" text,
  "password_hash" text,
  "invite_token_hash" text,
  "invite_expires" text,
  extra jsonb NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "full_name" text;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "email" text;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "role" text;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "status" text;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "project_ids" jsonb;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "google_sheet_id" text;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "designation" text;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "contact" text;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "hire_date" text;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "skills" text;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "password_hash" text;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "invite_token_hash" text;

ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "invite_expires" text;

CREATE INDEX IF NOT EXISTS "users_google_sheet_id_idx" ON "users" ("google_sheet_id");

CREATE UNIQUE INDEX IF NOT EXISTS "users_email_lower_idx" ON "users" (lower(email));

CREATE INDEX IF NOT EXISTS "daily_tasks_date_idx" ON "daily_tasks" ("date");

CREATE INDEX IF NOT EXISTS "tasks_status_idx" ON "tasks" ("status");

CREATE TABLE IF NOT EXISTS "uploaded_files" (
  id uuid PRIMARY KEY,
  created_date timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  mime text,
  data bytea NOT NULL
);
