// Writes src/themes/tailwind-palette.generated.js with the Tailwind colour scales the theme engine remaps at runtime.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);
const colors = require('tailwindcss/colors');
const FAMILIES = ['slate', 'gray', 'red', 'orange', 'amber', 'yellow', 'green', 'emerald', 'cyan', 'sky', 'blue', 'indigo', 'purple', 'pink'];
const out = Object.fromEntries(FAMILIES.map((f) => [f, colors[f]]));
const file = path.resolve(import.meta.dirname, '..', 'src/themes/tailwind-palette.generated.js');
fs.writeFileSync(file, `// GENERATED by scripts/build-palette.mjs (npm run build:palette). Default Tailwind colour scales.\nexport const FAMILIES = ${JSON.stringify(FAMILIES)};\nexport const DEFAULTS = ${JSON.stringify(out)};\n`);
console.log('palette written for', FAMILIES.length, 'families');
